### ISSUE TITLE
Sending and Receiving Simple Strings

### ISSUE THREAD

**Issue by notmike5** [matthew5025/trf7970a-cepas#1]
Which registers/methods/memory addresses, on an MSP432P401R, are used to send, receive, and/or store simple strings (i.e. 'Hello World!') between an NFC device and the MSP432? Ideally, I'd like to load the string somewhere, have it written to an NFC card, change modes, and then read the string back into the MSP432 after the card is brought back into proximity of the DLP-7970ABP.

**Comment by matthew5025** [comment]
Hey, this is a modified version of https://www.ti.com/lit/an/sloa208b/sloa208b.pdf?ts=1618426334300
The code here will not support NDEF.
I think the default TI NFCLink thing supports what you're looking for.
https://www.ti.com/lit/ug/slou452/slou452.pdf?ts=1618426456607
Downlaod Link: http://www.ti.com/lit/zip/sloa227
